### ISSUE TITLE
AttributeError: module 'BiliUtil' has no attribute 'Space'

### ISSUE THREAD

**Issue by zhaojiafu** [wolfbolin/BiliUtil#12]
import BiliUtil
# from BiliUtil import Album,Task
if __name__ == '__main__':
    album = BiliUtil.Album(3947271)
    # album = Album(3947271)
    album.set_album(3947271)
    album.set_by_url("https://www.bilibili.com/video/av3947271")
    album_info = album.sync()
    print(album_info)
    video_list = album.get_video_list()
    for video in video_list:
        video.sync(cookie="SESSDATA=fc1002e6%2C1570090626%2Cf55df891")
        task = BiliUtil.Task(video, 'D:/BiliUtil', album.aid)
        # task = Task(video, 'D:/BiliUtil', album.aid)
        task.start()

我下载好模块的之后，直接运行模块，报错了（After downloading the module, I ran the module directly and reported an error:）：

Error：

Traceback (most recent call last):
  File "D:/zjf_workspace/003、自己测试用的/006视频和音乐/02-bilibili视频/1、搜索key下載/2.4、BiliUtil模块下载视频.py", line 14, in <module>
    import BiliUtil
  File "D:\tools\Python3.6\lib\site-packages\BiliUtil\__init__.py", line 8, in <module>
    from BiliUtil.Space import User
  File "D:\tools\Python3.6\lib\site-packages\BiliUtil\Space\__init__.py", line 2, in <module>
    from .user import User
  File "D:\tools\Python3.6\lib\site-packages\BiliUtil\Space\user.py", line 6, in <module>
    import BiliUtil.Space as Space
AttributeError: module 'BiliUtil' has no attribute 'Space'

**Comment by wolfbolin** [comment]
请更新包到最新版本，2.0版本接口与旧版本不兼容，请参考最新的文档修改你的程序。

**Comment by KyunSmile** [comment]
> 请更新包到最新版本，2.0版本接口与旧版本不兼容，请参考最新的文档修改你的程序。

2019.12.16日安装的最新版本，问题与题主相同。
尝试运行的example4，但实际上import BiliUtil一行就直接报错了
----------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-ad14e4604037> in <module>()
      1 # coding=utf-8
----> 2 import BiliUtil
      3 from cookie import cookie
      4 
      5 user_list = [

~\Anaconda3\lib\site-packages\BiliUtil\__init__.py in <module>()
      6 from BiliUtil.Util import Config
      7 
----> 8 from BiliUtil.Space import User
      9 from BiliUtil.Space import Channel
     10 

~\Anaconda3\lib\site-packages\BiliUtil\Space\__init__.py in <module>()
      1 # coding=utf-8
----> 2 from .user import User
      3 from .channel import Channel

~\Anaconda3\lib\site-packages\BiliUtil\Space\user.py in <module>()
      4 from urllib import parse
      5 import BiliUtil.Util as Util
----> 6 import BiliUtil.Space as Space
      7 import BiliUtil.Video as Video
      8 

AttributeError: module 'BiliUtil' has no attribute 'Space'
