### ISSUE TITLE
Keyerroe['code']

### ISSUE THREAD

**Issue by lurchycc** [wolfbolin/BiliUtil#40]
Traceback (most recent call last):
  File "/home/amy/PycharmProjects/untitled/test.py", line 31, in <module>
    av_list = fetcher.fetch_all(cookie, BiliUtil.Config.SET_AS_NAME)
  File "/home/amy/anaconda3/lib/python3.8/site-packages/BiliUtil/Video/fetcher.py", line 46, in fetch_all
    album_list = self.obj.get_album_list()
  File "/home/amy/anaconda3/lib/python3.8/site-packages/BiliUtil/Space/user.py", line 99, in get_album_list
    json_data = Util.http_get(**http_request)
  File "/home/amy/anaconda3/lib/python3.8/site-packages/BiliUtil/Util/tools.py", line 192, in http_get
    elif json_data['code'] == -404 or json_data['code'] == -403:
KeyError: 'code'
************************************下面是example4的代码
# coding=utf-8
import BiliUtil

user_list = [
    # Up 的 Pid， Up的名字， 排除av列表
    ("210839932", "开箱喵可恩", []),
]

video_cache = r'./Bilibili'
cookie = "ABFA406E-6E16-5D05-843F-B8954CFE50D986234infoc"  # 假的

# 设置代理信息
# BiliUtil.Config.HTTP_PROXY = 'http://127.0.0.1:8888'
# BiliUtil.Config.HTTPS_PROXY = 'http://127.0.0.1:8888'

if __name__ == '__main__':
    # 初始化过滤器
    # 设置视频质量限制
    quality = [BiliUtil.Config.Quality.V360P,
               BiliUtil.Config.Quality.V480P]
    length = [40, 600]  # 设置视频长度
    ratio = [1, 2]  # 设置视频比例，只保留横屏
    video_filter = BiliUtil.Filter(quality=quality, length=length, ratio=ratio)

    # 扫描指定用户并下载
    # 模仿该方式，你也可以下载用户某个频道下的全部视频
    for up in user_list:
        print('正在下载用户:{} 的视频'.format(up[1]))
        user = BiliUtil.User(up[0])
        fetcher = BiliUtil.Fetcher(user)
        av_list = fetcher.fetch_all(cookie, BiliUtil.Config.SET_AS_NAME)
        print(av_list)
        positive_list, negative_list = fetcher.load_exist(video_cache)
        exclude_list = positive_list + up[2]
        task_list = fetcher.load_task(video_cache, exclude_list, video_filter)
        print(task_list)
        download_list = fetcher.pull_all()
        print('完成{}个视频下载：{}'.format(len(download_list), download_list))

**Comment by lurchycc** [comment]
当我把代理部分不注释掉时,会出现connection refuse

**Comment by xincheng213618** [comment]
这是因为你没有开代理

**Comment by dykw** [comment]
不开代理不能使用么

**Comment by xincheng213618** [comment]
你开代理就用，不开代理就注释掉代理部分啊
